# https://taskfile.dev

version: "3"

dotenv: [".env", "{{.ENV}}/.env", "{{.HOME}}/.env"]

tasks:
  default:
    cmds:
      - task: build

  check:
    desc: Check code & format
    cmds:
      - cargo check
      - cargo fmt --all -- --check
      - cargo clippy --all-targets --all-features

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  run:
    desc: Run the application
    cmds:
      - cargo run
  build:
    desc: Build for current target platform
    generates:
      - target/debug
    cmds:
      - cargo build --release

  cp_frontend_res:
    desc: Copy frontend resources to for embed
    cmds:
      - cp -r $FRONTEND_DIST_DIR frontend_dist

  rm_frontend_res:
    desc: Remove frontend resources
    cmds:
      - rm -rf frontend_dist
